
// ------------------------------------------------------------------ACTUAL CODE------------------------------------------------------------------



var weatherBox = document.querySelector('.weatherSection')
var cityTitle = document.querySelector('.cityTitle')
var clouds = document.querySelector('.clouds')
var boxcontain = document.querySelector('.databoxContainer')

var searchHistoryBtn;
var searchHistory = document.querySelector('.container2')


// Fetch promise function + appends data from API to Right side of screen





const getData = async () => {
    boxcontain.innerHTML = "";
   

    var query = document.querySelector('.queryInput').value
    
    try {
        const res = await fetch(
            `https://api.openweathermap.org/data/2.5/forecast?q=` + query + `&appid=302b19a6a4300fb8db031ad4aeaefe4c&units=imperial`

        )

        const data = await res.json();
        console.log(data)


        for (y = 0; y <1; y++){

            var createBtn = document.createElement('button')
            cityTitle.textContent = query
            createBtn.textContent = query
            searchHistory.appendChild(createBtn)
            // Throw the createBtn.textContent into 
        }

        
        for (i = 0; i < 5; i++) {

            // cityTitle.textContent = query
            var databox = document.createElement('div')
            var iconid = data.list[i].weather[0].icon
            var iconURL = `http://openweathermap.org/img/w/` + iconid + `.png`
            var temp = document.createElement('div')
            var clouds = document.createElement('div')
            var image = document.createElement('img')
            


            image.src = iconURL
            clouds.textContent = data.list[i].weather[0].description
            temp.textContent = data.list[i].main.temp

            boxcontain.appendChild(databox)
            databox.appendChild(clouds)
            databox.appendChild(temp)
            databox.appendChild(image)
            databox.style.paddingRight = "10px"

      
            
            
        }




    } catch (error) {
        console.log(error)
    }

}

// if (getData==true){


// }


var submitBut = document.querySelector('.citysearchBtn')

submitBut.addEventListener('click', getData)





            // Need to loop city search history and save to local storage, 
            // store line 84 as the save for quiery and append to a new button generated by the loop.
            //   Need on click function to run again. If than statements? 

            // --------Code for Search history------     
            // if (saveHistoryBtn('click', function{write savehistroybtn function here})),
            //  than query == button.textcontent,
            //  run getData function again
